from enum import Enum

MX_BAY_FEATURE_HDMI_OUT      = (1 << 0)
MX_BAY_FEATURE_HDMI_IN       = (1 << 1)
MX_BAY_FEATURE_AUDIO_DIG_OUT = (1 << 2)
MX_BAY_FEATURE_AUDIO_DIG_IN  = (1 << 3)
MX_BAY_FEATURE_AUDIO_ANA_OUT = (1 << 4)
MX_BAY_FEATURE_AUDIO_ANA_IN  = (1 << 5)
MX_BAY_FEATURE_IR_IN         = (1 << 6)
MX_BAY_FEATURE_IR_OUT        = (1 << 7)
MX_BAY_FEATURE_AUDIO_AMP_OUT = (1 << 8)
MX_BAY_FEATURE_RC_OUT        = (1 << 9)
MX_BAY_FEATURE_RC_IN         = (1 << 10)
MX_BAY_FEATURE_DOLBY         = (1 << 11)
MX_BAY_FEATURE_AUTO_OFF      = (1 << 12)
MX_BAY_FEATURE_DOLBY_IN_POS  = 24

MX_LINK_FEATURE_NONE          = 0
MX_LINK_FEATURE_VIDEO_HDMI    = (1 << 0)
MX_LINK_FEATURE_AUDIO_OPTICAL = (1 << 1)
MX_LINK_FEATURE_AUDIO_ANALOG  = (1 << 2)
MX_LINK_FEATURE_IR            = (1 << 3)
MX_LINK_FEATURE_RC            = (1 << 4)

class RCKey(Enum):
    KEY_0                = 0
    KEY_1                = 1
    KEY_2                = 2
    KEY_3                = 3
    KEY_4                = 4
    KEY_5                = 5
    KEY_6                = 6
    KEY_7                = 7
    KEY_8                = 8
    KEY_9                = 9
    KEY_SELECT           = 10
    KEY_BACK             = 11
    KEY_UP               = 12
    KEY_DOWN             = 13
    KEY_LEFT             = 14
    KEY_RIGHT            = 15
    KEY_MENU             = 16
    KEY_CONTENT_MENU     = 17
    KEY_CHANNEL_UP       = 18
    KEY_CHANNEL_DOWN     = 19
    KEY_PLAY             = 20
    KEY_PAUSE            = 21
    KEY_STOP             = 22
    KEY_RECORD           = 23
    KEY_FAST_FORWARD     = 24
    KEY_REWIND           = 25
    KEY_RED              = 26
    KEY_GREEN            = 27
    KEY_YELLOW           = 28
    KEY_BLUE             = 29
    KEY_HELP             = 30
    KEY_INFORMATION      = 31
    KEY_TEXT             = 32
    KEY_GUIDE            = 33
    KEY_VIDEO_ON_DEMAND  = 34
    KEY_PREVIOUS_CHANNEL = 80
    KEY_3D_MODE          = 81
    KEY_SUBTITLE         = 82
    KEY_SOUND_SELECT     = 83
    KEY_INPUT_SELECT     = 84
    KEY_EJECT            = 85
    KEY_NEXT_CHAPTER     = 86
    KEY_PREVIOUS_CHAPTER = 87
    KEY_CUSTOM_CEC       = 1280
    KEY_INTERACTIVE      = 128
    KEY_SEARCH           = 129
    KEY_SKY              = 130
    KEY_CUSTOM_SKY       = 2048

