from homeassistant.components.media_player.const import (
    SUPPORT_SELECT_SOURCE,
    SUPPORT_TURN_OFF,
    SUPPORT_TURN_ON,
    SUPPORT_VOLUME_MUTE,
    SUPPORT_VOLUME_SET,
    SUPPORT_VOLUME_STEP,
    SUPPORT_PLAY,
    SUPPORT_STOP,
)

DOMAIN = "mx_remote"
CONF_SERIAL = "serial"
SIGNAL_MXR_REGISTER = "mxr_new_player"
SIGNAL_MXR_REGISTER_VOLUME = "mxr_new_volume"
SIGNAL_MXR_DEV_UPDATE = "mxr_device_update"
SIGNAL_MXR_DEV_TEMPERATURE_UPDATE = "mxr_device_temperature_update"
SIGNAL_MXR_BAY_UPDATE = "mxr_bay_update"

SERVICE_SET_ROUTE  = "set_route"
SERVICE_MUTE       = "mute"
SERVICE_SET_VOLUME = "set_volume"

SUPPORT_BAY_VIDEO_INPUT = (
    SUPPORT_TURN_ON
    | SUPPORT_TURN_OFF
    | SUPPORT_PLAY
    | SUPPORT_STOP
)

SUPPORT_BAY_VIDEO_OUTPUT = (
    SUPPORT_VOLUME_MUTE
    | SUPPORT_VOLUME_STEP
    | SUPPORT_VOLUME_SET
    | SUPPORT_TURN_ON
    | SUPPORT_TURN_OFF
    | SUPPORT_PLAY
    | SUPPORT_STOP
    | SUPPORT_SELECT_SOURCE
)

SUPPORT_BAY_VIDEO_OUTPUT_AMP = (
    SUPPORT_VOLUME_MUTE
    | SUPPORT_VOLUME_STEP
    | SUPPORT_VOLUME_SET
    | SUPPORT_TURN_ON
    | SUPPORT_TURN_OFF
    | SUPPORT_PLAY
    | SUPPORT_STOP
    | SUPPORT_SELECT_SOURCE
)

SUPPORT_BAY_AUDIO_OUTPUT = (
    SUPPORT_VOLUME_MUTE
    | SUPPORT_VOLUME_STEP
    | SUPPORT_VOLUME_SET
    | SUPPORT_TURN_ON
    | SUPPORT_TURN_OFF
)

SUPPORT_BAY_VIDEO_AUDIO_OUTPUT = (
    SUPPORT_VOLUME_MUTE
    | SUPPORT_VOLUME_STEP
    | SUPPORT_VOLUME_SET
    | SUPPORT_TURN_ON
    | SUPPORT_TURN_OFF
    | SUPPORT_SELECT_SOURCE
)

SUPPORT_P8AMP = (
    SUPPORT_VOLUME_MUTE
    | SUPPORT_VOLUME_STEP
    | SUPPORT_VOLUME_SET
)

SUPPORT_P8MATRIX = (
    SUPPORT_SELECT_SOURCE
    | SUPPORT_TURN_ON
    | SUPPORT_TURN_OFF
)

