set_route:
  description: Change the route without powering on the sink.
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: mx_remote
          domain: media_player
    source:
      description: Name of the source
      example: 'Input 5'
      required: true
    power:
      description: Auto power on
      example: true
      default: true
      required: false
      selector:
        select:
          options:
            - true
            - false
mute:
  description: Mute or restore volume
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: mx_remote
          domain: media_player
    mute:
      description: True to mute, false to restore
      example: true
      default: true
      required: true
      selector:
        select:
          options:
            - true
            - false

set_volume:
  description: Change volume level
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: mx_remote
          domain: media_player
    volume:
      description: New volume level
      example: 0.48
      default: true
      required: true
